In [10]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [3]:
iris = load_iris()

**Logistic Regression**

In [11]:
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_scores

array([ 0.96078431,  0.92156863,  0.95833333])

In [12]:
np.average(l_scores)

0.94689542483660138

**Decision Tree**

In [13]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_scores

array([ 0.98039216,  0.92156863,  1.        ])

In [14]:
np.average(d_scores)

0.9673202614379085

**Support Vector Machine (SVM)**

In [15]:
s_scores = cross_val_score(SVC(), iris.data, iris.target)
s_scores

array([ 0.98039216,  0.96078431,  0.97916667])

In [16]:
np.average(s_scores)

0.97344771241830064

**Random Forest**

In [34]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=10), iris.data, iris.target)
r_scores

array([ 0.98039216,  0.92156863,  0.97916667])

In [35]:
np.average(r_scores)

0.96037581699346397

**Best score so far is from SVM: 0.97344771241830064**