In [5]:
# Importing numpy as np
import numpy as np

### Define Matrices

In [6]:
A = np.array([[5, 2, 1],
              [7, 5, -3]])

B = np.array([[4, -1],
              [6, 5],
              [-4, 3]])

print(f'Matrix A: \n{A} \n shape: {A.shape}')
print(f'Matrix B: \n{B} \n shape: {B.shape}')

Matrix A: 
[[ 5  2  1]
 [ 7  5 -3]] 
 shape: (2, 3)
Matrix B: 
[[ 4 -1]
 [ 6  5]
 [-4  3]] 
 shape: (3, 2)


### Dot Product

[Wikipedia Article](https://en.wikipedia.org/wiki/Dot_product)

In [7]:
C = np.dot(A, B)

print(f'Matrix A * Matrix B: \n{C} \n shape: {C.shape}')

D = np.dot(B, A)

print(f'Matrix B * Matrix A: \n{D} \n shape: {D.shape}')

Matrix A * Matrix B: 
[[28  8]
 [70  9]] 
 shape: (2, 2)
Matrix B * Matrix A: 
[[ 13   3   7]
 [ 65  37  -9]
 [  1   7 -13]] 
 shape: (3, 3)


### Rank and Trace

[Rank Wikipedia Article](https://en.wikipedia.org/wiki/Rank_(linear_algebra)k)

[Trace Wikipedia Article](https://en.wikipedia.org/wiki/Trace_(linear_algebra))

In [9]:

# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))

print("Rank of B:", np.linalg.matrix_rank(B))
 
# Trace of matrix A
print("\nTrace of C:", np.trace(C))

print("Trace of D:", np.trace(D))
 

Rank of A: 2
Rank of B: 2

Trace of C: 37
Trace of D: 37


### Determinant

[Wikipedia Article](https://en.wikipedia.org/wiki/Determinant)

In [12]:
print(f'The determinant of the matrix C is {np.linalg.det(C)}')

print(f'The determinant of the matrix D is {np.linalg.det(D)}')

The determinant of the matrix C is -308.0000000000001
The determinant of the matrix D is -7.425171588693042e-13


### Inverse 

In [14]:
E = np.linalg.inv(C)

print(f'The inverse of the matrix C is \n{E}')

print(f'The inverse of the matrix D is \n{np.linalg.inv(D)}')

The inverse of the matrix C is 
[[-0.02922078  0.02597403]
 [ 0.22727273 -0.09090909]]
The inverse of the matrix D is 
[[ 5.62949953e+14 -1.18515780e+14  3.85176284e+14]
 [-1.12589991e+15  2.37031559e+14 -7.70352568e+14]
 [-5.62949953e+14  1.18515780e+14 -3.85176284e+14]]


Check that $C . C^{-1} = I$

In [15]:
print(np.dot(C, E))

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
