<h1 style="color:green" align='center'>Numpy tutorial: iterate numpy array using nditer</h1>

In [27]:
import numpy as np

In [28]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

<h3 style="color:purple">Using normal for loop iteration</h3>

In [29]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


<h3 style="color:purple">For loop with flatten</h3>

In [30]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


<h1 style="color:blue" align="center">nditer</h1>

<h3 style="color:purple">C style ordering</h3>

In [31]:
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


<h2 style="color:purple">Fortan style ordering</h2>

In [32]:
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


<h3 style="color:purple">external_loop</h3>

In [33]:
for x in np.nditer(a, flags=['external_loop'],order='F'):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


<h2 style="color:purple">Modify array values while iterating</h2>

In [34]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x

In [35]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

<h2 style="color:purple">Iterate two broadcastable arrays concurrently</h2>

In [36]:
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [37]:
for x, y in np.nditer([a,b]):
    print (x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
