In [1]:
import numpy as np

In [26]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

<h2 style="color:purple">C style ordering</h2>

In [27]:
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


<h2 style="color:purple">Fortan style ordering</h2>

In [28]:
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


<h2 style="color:purple">Modify array values while iterating</h2>

In [33]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x + 1

In [34]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

<h2 style="color:purple">Iterate two broadcastable arrays concurrently</h2>

In [35]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])